"""测试 maw/runtimes/freezer.py（通用冻结器：声明驱动命令 + CPU 变体生成）。"""

from __future__ import annotations

import tempfile
import unittest
import unittest.mock
from pathlib import Path

from maw.runtimes import freezer as freezer_mod
from maw.runtimes.base import RuntimeSpec
from maw.runtimes.local_spec import LOCAL_SPEC
from maw.runtimes.ocr_spec import OCR_SPEC
from maw.runtimes.moss_spec import MOSS_SPEC

UV = Path("C:/tools/uv.exe")
BUILD = Path("repo/build")

MOSS_IN = """\
# MOSS 依赖声明（GPU 分支 pin cu130 本地版本）。
av>=14.0
torch==2.13.0+cu130; sys_platform != 'darwin'
torch>=2.13.0; sys_platform == 'darwin'
torchaudio==2.11.0+cu130; sys_platform != 'darwin'
torchaudio>=2.11.0; sys_platform == 'darwin'
safetensors>=0.6.2
"""

EXPORT_SAMPLE = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --extra local
accelerate==1.12.0 \\
    --hash=sha256:abc123
    # via
    #   moys-asr-workflow
    #   qwen-asr
gradio==6.17.3 \\
    --hash=sha256:def456
    # via qwen-asr
torch==2.13.0+cu130 ; sys_platform != 'darwin' \\
    --hash=sha256:eee789
    # via
    #   accelerate
    #   moys-asr-workflow
audioop-lts==0.2.2 ; python_full_version >= '3.13' \\
    --hash=sha256:fff000
    # via funasr
funasr==1.4.2 \\
    --hash=sha256:abc111
    # via moys-asr-workflow
"""


class StripGpuPinsTests(unittest.TestCase):
    def test_strips_local_version_suffix_from_dependency_lines(self) -> None:
        self.assertEqual(
            freezer_mod.strip_gpu_pins("torch==2.13.0+cu130\n"),
            "torch==2.13.0\n",
        )

    def test_keeps_comment_lines_untouched(self) -> None:
        text = "# torch==2.13.0+cu130 注释里的说明文字\nav>=14.0\n"
        self.assertEqual(freezer_mod.strip_gpu_pins(text), text)

    def test_no_cu_pin_is_identity(self) -> None:
        text = "numba>=0.61.0\ntransformers>=5.6.0,<6.0.0\n"
        self.assertEqual(freezer_mod.strip_gpu_pins(text), text)


class CpuRequirementsLinesTests(unittest.TestCase):
    def test_moss_input_drops_darwin_branch_and_strips_marker_and_cu(self) -> None:
        lines = freezer_mod.cpu_requirements_lines(MOSS_IN)
        # 源注释不带入（头部注释由 cpu_input_text 负责），darwin 分支丢弃，
        # 剩余依赖行无 marker / 无 +cu
        self.assertNotIn("# MOSS 依赖声明（GPU 分支 pin cu130 本地版本）。", lines)
        self.assertEqual(lines, ["av>=14.0", "torch==2.13.0", "torchaudio==2.11.0", "safetensors>=0.6.2"])
        self.assertNotIn("sys_platform", "".join(lines))
        self.assertNotIn("+cu130", "".join(lines))
        self.assertNotIn("darwin", "".join(lines))

    def test_export_pin_lines_also_cpu_normalized(self) -> None:
        lines = freezer_mod.cpu_requirements_lines(
            "torch==2.13.0+cu130 ; sys_platform != 'darwin'\n"
            "torch==2.13.0 ; sys_platform == 'darwin'\n"
            "audioop-lts==0.2.2 ; python_full_version >= '3.13'\n"
        )
        # darwin 分支丢弃；!= darwin 条件剥离；无关 marker 保留
        self.assertEqual(lines, ["torch==2.13.0", "audioop-lts==0.2.2 ; python_full_version >= '3.13'"])

    def test_cpu_input_text_ends_with_lf_and_accepts_header(self) -> None:
        text = freezer_mod.cpu_input_text(MOSS_IN, header="# CPU 变体\n")
        self.assertTrue(text.endswith("\n"))
        self.assertTrue(text.startswith("# CPU 变体\n"))
        self.assertIn("torch==2.13.0\n", text)


class DirectPinsFromExportTests(unittest.TestCase):
    def test_extracts_direct_pins_only(self) -> None:
        pins = freezer_mod.direct_pins_from_export(EXPORT_SAMPLE)
        self.assertEqual(
            pins,
            [
                "accelerate==1.12.0",
                "torch==2.13.0+cu130 ; sys_platform != 'darwin'",
                "funasr==1.4.2",
            ],
        )

    def test_empty_input(self) -> None:
        self.assertEqual(freezer_mod.direct_pins_from_export(""), [])


class FreezeCommandTests(unittest.TestCase):
    def test_local_main_uses_uv_export(self) -> None:
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, LOCAL_SPEC, BUILD),
            [str(UV), "export", "--frozen", "--extra", "local", "--no-dev",
             "--format", "requirements-txt", "-o", str(BUILD / "requirements-local.txt")],
        )

    def test_ocr_main_uses_uv_export(self) -> None:
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, OCR_SPEC, BUILD),
            [str(UV), "export", "--frozen", "--extra", "ocr", "--no-dev",
             "--format", "requirements-txt", "-o", str(BUILD / "requirements-ocr.txt")],
        )

    def test_moss_main_compiles_in_file_with_cu130_index(self) -> None:
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, MOSS_SPEC, BUILD),
            [str(UV), "pip", "compile", "moss-requirements.in", "-p", "3.11",
             "--extra-index-url", "https://download.pytorch.org/whl/cu130",
             "--index-strategy", "unsafe-best-match",
             "-o", str(BUILD / "requirements-moss.txt")],
        )

    def test_cpu_variants_compile_generated_input_in_build_dir(self) -> None:
        for spec, name in ((LOCAL_SPEC, "local"), (MOSS_SPEC, "moss")):
            with self.subTest(spec=spec.key):
                self.assertEqual(
                    freezer_mod.cpu_freeze_command(UV, spec, BUILD),
                    [str(UV), "pip", "compile", str(BUILD / f"{name}-cpu-requirements.in"),
                     "-p", "3.11", "--generate-hashes",
                     "--index-strategy", "unsafe-best-match",
                     "-o", str(BUILD / f"requirements-{name}-cpu.txt")],
                )

    def test_ocr_has_no_cpu_variant(self) -> None:
        self.assertIsNone(freezer_mod.cpu_freeze_command(UV, OCR_SPEC, BUILD))


class EnsureFrozenTests(unittest.TestCase):
    def _temp_build_dir(self) -> Path:
        build = Path(tempfile.mkdtemp()) / "build"
        build.mkdir(parents=True)
        self.addCleanup(lambda: __import__("shutil").rmtree(build.parent, ignore_errors=True))
        return build

    def _fake_run(self, calls: list[list[str]]) -> object:
        def run(command: list[str]) -> object:
            calls.append(command)
            index = command.index("-o")
            Path(command[index + 1]).write_text(EXPORT_SAMPLE, encoding="utf-8")
            return 0

        return run

    def test_main_generated_when_missing_and_skipped_when_present(self) -> None:
        build = self._temp_build_dir()
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, LOCAL_SPEC, cpu=False, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(calls[0][1:3], ["export", "--frozen"])
        # 已存在则不再触发
        before = len(calls)
        freezer_mod.ensure_frozen(UV, LOCAL_SPEC, cpu=False, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(len(calls), before)

    def test_local_cpu_exports_main_first_then_compiles(self) -> None:
        build = self._temp_build_dir()
        calls: list[list[str]] = []
        emitted: list[str] = []
        freezer_mod.ensure_frozen(
            UV, LOCAL_SPEC, cpu=True, build_dir=build,
            run=self._fake_run(calls),
            emit=emitted.append,
        )
        # 先 export 主清单（提取直接依赖的源），再 compile CPU 变体
        self.assertEqual(calls[0][1:3], ["export", "--frozen"])
        self.assertEqual(calls[1][1:3], ["pip", "compile"])
        self.assertIn("--generate-hashes", calls[1])
        # 生成式 in 文件已落盘，且内容被 CPU 归一化（无 +cu130）
        cpu_in = build / "local-cpu-requirements.in"
        self.assertTrue(cpu_in.is_file())
        content = cpu_in.read_text(encoding="utf-8")
        self.assertIn("funasr==1.4.2", content)
        self.assertIn("torch==2.13.0", content)
        self.assertNotIn("+cu130", content)
        self.assertIn("正在生成", "".join(emitted))

    def test_local_cpu_reuses_existing_main_export(self) -> None:
        build = self._temp_build_dir()
        (build / "requirements-local.txt").write_text(EXPORT_SAMPLE, encoding="utf-8")
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, LOCAL_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))
        # 主清单已存在，只执行 compile
        self.assertEqual(len(calls), 1)
        self.assertEqual(calls[0][1:3], ["pip", "compile"])

    def test_moss_cpu_derives_input_from_in_file(self) -> None:
        build = self._temp_build_dir()
        in_path = build.parent / "moss-requirements.in"
        in_path.write_text(MOSS_IN, encoding="utf-8")
        calls: list[list[str]] = []

        with unittest.mock.patch.object(
            freezer_mod.Path, "read_text", autospec=True
        ) as read_text:
            read_text.side_effect = lambda self, **kw: (
                MOSS_IN if Path(self).name == "moss-requirements.in" else "unexpected"
            )
            freezer_mod.ensure_frozen(UV, MOSS_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))

        self.assertEqual(len(calls), 1)
        self.assertEqual(calls[0][1:3], ["pip", "compile"])
        self.assertNotIn("extra-index-url", calls[0])
        cpu_in = build / "moss-cpu-requirements.in"
        self.assertTrue(cpu_in.is_file())
        content = cpu_in.read_text(encoding="utf-8")
        self.assertIn("torch==2.13.0\n", content)
        self.assertNotIn("; sys_platform", content)

    def test_ocr_cpu_variant_never_runs(self) -> None:
        build = self._temp_build_dir()
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, OCR_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(calls, [])

    def test_existing_cpu_txt_skips_generation(self) -> None:
        build = self._temp_build_dir()
        (build / "requirements-moss-cpu.txt").write_text("torch==2.13.0\n", encoding="utf-8")
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, MOSS_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(calls, [])


class RuntimeSpecDefaultsTests(unittest.TestCase):
    def test_new_fields_default_to_export_recipe(self) -> None:
        spec = RuntimeSpec(
            key="x", runtime_version="1", python_version="3.11",
            embed_python_zip="", requirements_emit="", requirements_key="x",
            requirements_bundle_name="requirements-x.txt", verify_command="",
            package_dirs=(), worker_module="", message_prefix="", feature_label="",
            missing_detail="", ready_detail="", fix_action_label="",
            ready_emit_done="", dir_name="x", root_env="MAW_X_ROOT", bundle_dir="x",
        )
        self.assertIsNone(spec.requirements_in)
        self.assertEqual(spec.requirements_in_args, ())
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, spec, BUILD)[1:3],
            ["export", "--frozen"],
        )


if __name__ == "__main__":
    unittest.main()